name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - uses: gradle/gradle-build-action@v3.5.0
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew testdebug

      - name: Build with Gradle
        run: |
          ./gradlew --scan --stacktrace \
              :app:assembleDebug
